ScrollReveal({ reset: true });
ScrollReveal().reveal(".introduction", { distance: "60px" });
ScrollReveal().reveal(".introduction-2", { distance: "60px" });
ScrollReveal().reveal(".cloud-1", { scale: 0.85 });
ScrollReveal().reveal(".cloud-2", { scale: 0.85 });
ScrollReveal().reveal(".cloud-3", { scale: 0.85 });
ScrollReveal().reveal(".tree", { scale: 0.85 });
ScrollReveal().reveal(".profile", { distance: "60px" });
ScrollReveal().reveal(".skills", { distance: "60px" });
ScrollReveal().reveal(".skills-row-1", { distance: "60px" });
ScrollReveal().reveal(".skills-row-2", { distance: "60px" });
ScrollReveal().reveal(".skills-row-3", { distance: "60px" });
ScrollReveal().reveal(".portfolio", { distance: "60px" });
ScrollReveal().reveal(".portfolio-row-1", { distance: "60px" });
ScrollReveal().reveal(".portfolio-row-2", { distance: "60px" });
ScrollReveal().reveal(".portfolio-row-3", { distance: "60px" });
ScrollReveal().reveal(".contact-me", { distance: "60px" });
ScrollReveal().reveal(".footer-all", { distance: "60px" });
ScrollReveal().reveal(".bottom-container p", { distance: "60px" });
